// layout.tsx
import type { Metadata } from "next/font";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        {/* Sticky Navbar */}
        <Navbar/>

        <div className="min-h-screen" style={{
            background: 'linear-gradient(135deg,rgb(40, 98, 173) 0%, #032859 50%, #032859 100%)', // Use the dark blue gradient
            color: '#FFFFFF' // Set default text color to white
        }}>
            {children}
        </div>
        </body>
        </html>
    );
}